- name: Demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: print fruit name
      ansible.builtin.debug:
        msg: fruitName - {{ item }}
      loop:
        - apple
        - orange
        - grape
        - banana
    - name: print fruit name with quantity
      ansible.builtin.debug:
        msg: fruitName - {{ item - name }}, quantity - {{ item - quantity }}
      loops:
        -{ name:apple, quantity:100 }
        -{ name:orange, quantity:200 }
        -{ name:grape, quantity:100 }
        -{ name:banana, quantity:400 }

